### ISSUE TITLE
Rxjava 使用疑惑

### ISSUE THREAD

**Issue by stqb12** [18Gray/ProCamera#17]
ProCamera/app/src/main/java/com/eighteengray/procamera/business/AlbumBusiness.java
看了这个我就不懂了？到底哪个rxjava在哪个call中进行耗时操作呢？据我的理解，`subcribe() new Action1<Cursor>()`是在`Obseveron()`调度器中执行的？如果确实如此，这里为何用rxjava呢？请指教一下，谢谢

**Comment by 18Gray** [comment]
RxJava准确来说是用于异步操作，而不单指耗时操作。这里使用RxJava就是执行取相册图片数据这个异步操作，再加上监听机制，让UI层在数据回调后完成渲染。

**Comment by stqb12** [comment]
你好，谢谢你提供这么完美的相机库。言语上表达有些困难，代码上才能更好表达。我想表达的是，不应该把所有的操作都放在UI线程中，这样Rxjava的作用并不大。我对代码修改了一下，你看合理不。

**Comment by 18Gray** [comment]
恩，非常感谢能参与到这个项目中，出于对拍照的喜爱所以决定去挖掘camera2的相机潜力。最近工作比较紧张，回复较慢，代码更新也慢了，会不断完善的。
