### ISSUE TITLE
最低支持的设备是多少,刚刚接触相机开发,打算拿你的项目来抽离增加

### ISSUE THREAD

**Issue by dyfan** [18Gray/ProCamera#19]
如题,不知道camera2在L以下设备是否支持.预览相机画面部分机型会有问题. = = 很强大的学习资源.虽然代码乱了点,(捂脸表情),不过很好的.

**Comment by 18Gray** [comment]
camera2 api最低支持5.0sdk，可以直接用TextrureView中的方法，因为用了比较多的抽象所以刚看可能不太好看明白。

**Comment by dyfan** [comment]
手机版本5.0以下就不可以用了么..

**Comment by 18Gray** [comment]
嗯，camera2 api是5.0以上手机才有

**Comment by dyfan** [comment]
= =  这就比较尴尬了 我关闭啦
